#!/bin/bash

algo="milp"
t="$1"
m="$2"
n="$3"
r="$4"

bazel build --cxxopt='-std=c++14' --compilation_mode=opt -- //...
for s in {1..5}; do
    echo -n "${t}${m}${n}${r}${s},"
    ./bazel-bin/lib/generator_main -n ${n} -m ${m} -t ${t} -r ${r} -s ${s} -o "ins.txt" > /dev/null
    ./bazel-bin/lib/main \
        -a "${algo}" \
        -o "out.ini" \
        -i "ins.txt"
    sed -nr "/^\[Solution\]/ { :l /^Time[ ]*=/ { s/.*=[ ]*//; p; q;}; n; b l;}" "out.ini"
    #../gap-solver/solve "ins.txt" -1 100 -1 5
done

