#!/usr/bin/python3

import sys
import os
import configparser

algo = sys.argv[1]
t = 120;
data = [
        "a05100", "a10100", "a20100",
        "a05200", "a10200", "a20200",
        "b05100", "b10100", "b20100",
        "b05200", "b10200", "b20200",
        "c05100", "c10100", "c20100",
        "c05200", "c10200", "c20200",
        "c10400", "c20400", "c40400",
        "c15900", "c30900", "c60900",
        "c201600", "c401600", "c801600",
        "d05100", "d10100", "d20100",
        "d05200", "d10200", "d20200",
        "d10400", "d20400", "d40400",
        "d15900", "d30900", "d60900",
        "d201600", "d401600", "d801600",
        "e05100", "e10100", "e20100",
        "e05200", "e10200", "e20200",
        "e10400", "e20400", "e40400",
        "e15900", "e30900", "e60900",
        "e201600", "e401600", "e801600"]

os.system('bazel build --cxxopt=\'-std=c++14\' --compilation_mode=opt -- //lib:main')

for i in data:
    certfile = "out/solutions_" + algo + "_" + str(t) + "/" + i + "_solution.txt"
    inifile  = "out/solutions_" + algo + "_" + str(t) + "/" + i + "_output.ini"
    # print(i + ",", end="")
    os.system("./bazel-bin/lib/main"
        + " -a \"" + algo + "\""
        + " -t " + str(t)
        + " -i \"data/" + i + "\""
        + " -c \"" + certfile + "\""
        + " -o \"" + inifile + "\"")
    ini = configparser.ConfigParser()
    ini.read(inifile)
    if ini.has_section("Solution"):
        if ini["Solution"]["Feasible"] == "True":
            print(ini["Solution"]["Cost"], end="")
        else:
            print(-1, end="")
        print("," + ini["Solution"]["Time"])
    else:
        print(ini["Bound"]["Cost"], end="")
        print("," + ini["Bound"]["Time"])

