#!/usr/bin/python3

import sys
import os
import os.path
import configparser

data = [
        "a05100", "a10100", "a20100",
        "a05200", "a10200", "a20200",
        "b05100", "b10100", "b20100",
        "b05200", "b10200", "b20200",
        "c05100", "c10100", "c20100",
        "c05200", "c10200", "c20200",
        "c10400", "c20400", "c40400",
        "c15900", "c30900", "c60900",
        "c201600", "c401600", "c801600",
        "d05100", "d10100", "d20100",
        "d05200", "d10200", "d20200",
        "d10400", "d20400", "d40400",
        "d15900", "d30900", "d60900",
        "d201600", "d401600", "d801600",
        "e05100", "e10100", "e20100",
        "e05200", "e10200", "e20200",
        "e10400", "e20400", "e40400",
        "e15900", "e30900", "e60900",
        "e201600", "e401600", "e801600"]

algo = sys.argv[1]
t = ""
if (len(sys.argv) > 2):
    t = sys.argv[2]

os.system('bazel build -- //lib:main')
suffix = algo.replace(" ", "_").replace("/", "_")
if t == "":
    outdir = os.path.join("out", suffix)
    time_limit = ""
else:
    outdir = os.path.join("out", suffix + "_" + t)
    time_limit = " -t " + str(t)
os.makedirs(outdir, exist_ok=True)

for i in data:
    certfile = os.path.join(outdir, i + "_solution.txt")
    inifile  = os.path.join(outdir, i + "_output.ini")
    os.system("./bazel-bin/lib/main -u"
        + " -a \"" + algo + "\""
        + time_limit
        + " -i \"data/" + i + "\""
        # + " -c \"" + certfile + "\""
        + " -o \"" + inifile + "\"")

    ini = configparser.ConfigParser()
    ini.read(inifile)
    if ini.has_section("Solution"):
        if ini["Solution"]["Feasible"] == "True":
            print(ini["Solution"]["Cost"], end="")
        else:
            print(-1, end="")
        print("," + ini["Solution"]["Time"])
    else:
        print(ini["Bound"]["Cost"], end="")
        print("," + ini["Bound"]["Time"])

