cc_library(
        name = "ls_ejectionchain",
        hdrs = ["ls_ejectionchain.hpp"],
        srcs = ["ls_ejectionchain.cpp"],
        deps = [
                "//lib:cpp",
                "//lb_linrelax_clp:linrelax_clp",
                "//ub_random:random",
                "//ub_ls_shiftswap:ls_shiftswap",
        ],
        visibility = ["//visibility:public"],
        include_prefix = "gap/ub_ls_ejectionchain/",
)

