cc_library(
        name = "vnsbranching_cbc",
        hdrs = ["vnsbranching_cbc.hpp"],
        srcs = ["vnsbranching_cbc.cpp"],
        deps = [
                "//lib:cpp",
                "//ub_random:random",
                "//ub_repair:repair",
                "//ub_ls_shiftswap:ls_shiftswap",
                "//opt_branchandcut_cbc:branchandcut_cbc",
        ],
        visibility = ["//visibility:public"],
        include_prefix = "gap/ub_vnsbranching_cbc/",
)

