cc_library(
        name = "ls_shiftswap",
        hdrs = ["ls_shiftswap.hpp"],
        srcs = ["ls_shiftswap.cpp"],
        deps = [
                "//lib:cpp",
                "//lb_linrelax_clp:linrelax_clp",
                "//ub_random:random",
        ],
        visibility = ["//visibility:public"],
        include_prefix = "gap/ub_ls_shiftswap/",
)

