cc_library(
        name = "lssimple",
        hdrs = ["lssimple.hpp"],
        srcs = ["lssimple.cpp"],
        deps = [
                "//lib:cpp",
                "//ub_random:random",
        ],
        visibility = ["//visibility:public"],
        include_prefix = "gap/ub_lssimple/",
)

