cc_library(
        name = "ls_ejectionchains",
        hdrs = ["ls_ejectionchains.hpp"],
        srcs = ["ls_ejectionchains.cpp"],
        deps = [
                "//lib:cpp",
                "//lb_linrelax_clp:linrelax_clp",
                "//ub_random:random",
        ],
        visibility = ["//visibility:public"],
        include_prefix = "gap/ub_ls_ejectionchains/",
)

