cc_library(
        name = "localsearch",
        hdrs = ["localsearch.hpp"],
        srcs = ["localsearch.cpp"],
        deps = [
                "//lib:cpp",
                "//ub_random:random",
        ],
        visibility = ["//visibility:public"],
        include_prefix = "gap/ub_localsearch/",
)

